//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDiem
    {
        public int MaDiaDiem { get; set; }
        public string TenThanhPho { get; set; }
        public int MaKhachSan { get; set; }
    
        public virtual KhachSan KhachSan { get; set; }
    }
}
