//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONTHANHTOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONTHANHTOAN()
        {
            this.PHONGs = new HashSet<PHONG>();
            this.PHUONGTIENDICHUYENs = new HashSet<PHUONGTIENDICHUYEN>();
        }
    
        public int MaDonThanhToan { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThucHienThanhToan { get; set; }
        public Nullable<decimal> SoTienThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONG> PHONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHUONGTIENDICHUYEN> PHUONGTIENDICHUYENs { get; set; }
    }
}
