//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public int MaPhong { get; set; }
        public string LoaiPhong { get; set; }
        public Nullable<decimal> GiaPhong { get; set; }
        public string TinhTrangPhong { get; set; }
        public Nullable<int> SoLuongKhach { get; set; }
        public string MoTaChiTietPhong { get; set; }
        public string Anh { get; set; }
        public Nullable<int> MaDonThanhToan { get; set; }
    
        public virtual DonThanhToan DonThanhToan { get; set; }
    }
}
