//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUONGTIENDICHUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHUONGTIENDICHUYEN()
        {
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
        }
    
        public int MaPhuongTienDiChuyen { get; set; }
        public string LoaiPhuongTien { get; set; }
        public Nullable<System.DateTime> ThoiGianKhoiHanh { get; set; }
        public Nullable<System.DateTime> ThoiGianDen { get; set; }
        public decimal Gia { get; set; }
        public Nullable<int> SoChoNgoiConTrong { get; set; }
        public Nullable<int> TongSoChoNgoi { get; set; }
        public string MoTaChiTiet { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaDonThanhToan { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual DONTHANHTOAN DONTHANHTOAN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
