//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuongTienDiChuyen
    {
        public int MaPhuongTienDiChuyen { get; set; }
        public string LoaiPhuongTien { get; set; }
        public Nullable<System.DateTime> ThoiGianKhoiHanh { get; set; }
        public Nullable<System.DateTime> ThoiGianDen { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> SoChoNgoiConTrong { get; set; }
        public Nullable<int> TongSoChoNgoi { get; set; }
        public string MoTaChiTiet { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<int> MaDonThanhToan { get; set; }
    
        public virtual DonThanhToan DonThanhToan { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
