//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIENNGHIKHACHSAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIENNGHIKHACHSAN()
        {
            this.SUDUNGs = new HashSet<SUDUNG>();
        }
    
        public int MaTienNghiKhachSan { get; set; }
        public string TenTienNghiKhachSan { get; set; }
        public int MaKhachHang { get; set; }
        public Nullable<int> MaKhachSan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUDUNG> SUDUNGs { get; set; }
    }
}
